version: '3'

volumes:
  wordpress:
    name: worpress
    driver: local
    driver_opts:
      device: /Users/${USER}/Desktop/Inception/src/wordpress
      o: bind
      type: none

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /Users/${USER}/Desktop/Inception/src/mariadb
      o: bind
      type: none

  networks:
    inception:
      name: inception

services:
  nginx:
    container_name: nginx
    build: ./src/requirements/nginx/Dockerfile
    image: nginx:42
    ports:
      - "443:443"
    depends_on:
      - mariadb
    volumes:
      - ./nginx/etc/nginx/conf.d
    networks: 
      - inception
    env_file:
      - .env
    restart: always

  mariadb:
    container_name: mariadb
    build: ./src/requirements/MariaDB/Dockerfile
    image: mariadb:42
    volumes: ./mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
  
  wordpress:
    container_name: wordpress
    build: ./src/requirements/Wordpress/Dockerfile
    image: wordpress:42
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always